version: "3.8"

services:
  # app:
  #   build: .
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    # ports:
    #   - "3000:3000"
    # env_file:
    #   - .env.development
    # depends_on:
    #   - db
    # networks:
    #   - nsl-network

  db:
    image: postgres:15
    restart: always
    container_name: nsl-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - nsl-network
  
  redis:
    image: redis:7
    restart: always
    container_name: nsl-redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    networks:
        - nsl-network


  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   restart: always
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - db
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   networks:
  #     - nsl-network

volumes:
  db_data:
  pgadmin-data:
networks:
  nsl-network:
    driver: bridge
