export const TYPES = {
    Logger: Symbol.for("Logger"),
    PrismaClient: Symbol.for("PrismaClient"),
    JwtService: Symbol.for("JwtService"),
    MailService: Symbol.for("MailService"),
    RedisService: Symbol.for("RedisService"),
    R2Service: Symbol.for("R2Service"),
    QueueService: Symbol.for("QueueService"),
    AuthMiddleware: Symbol.for("AuthMiddleware"),
    UserService: Symbol.for("UserService"),
    UserRepository: Symbol.for("UserRepository"),
    AuthService: Symbol.for("AuthService"),
    AuthRepository: Symbol.for("AuthRepository"),
    RoleService: Symbol.for("RoleService"),
    RoleRepository: Symbol.for("RoleRepository"),
    CategoryService: Symbol.for("CategoryService"),
    CategoryRepository: Symbol.for("CategoryRepository"),
    ProductService: Symbol.for("ProductService"),
    ProductRepository: Symbol.for("ProductRepository"),
};
